# config
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- .aider.*

# content
title: Felix Neumann
description: Software Developer
email:
  local_part: webmaster
  domain_part: fxnn.de
location: Brandenburg, Germany
social_media:
  linkedin_url: https://www.linkedin.com/in/fxneumann/
  mastodon_url: https://hachyderm.io/@fxnn
  instagram_url: https://www.instagram.com/fxnn.de/
  pixelfed_url: https://pixelfed.social/fxnn

# theming
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
