# config
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile

# content
title: Max Mustermann | Persönönliche Website
description: Webentwickler & Digitalstratege

# theming
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
