# config
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile

# content
title: Felix Neumann
description: Webentwickler & Digitalstratege
email: webmaster@fxnn.de
location: Brandenburg, Germany

# theming
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
